[package]
name = "jnix-macros"
version = "0.1.0"
authors = ["Janito Vaqueiro Ferreira Filho <janito@mullvad.net>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = "1"
