[package]
name = "jnix"
version = "0.1.0"
authors = ["Mullvad VPN <admin@mullvad.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jni = "0.13"
